import 'package:flutter/material.dart';

/// Material Design 3 Color Scheme for LangCurve
/// Primary Color: "Tím đất" (#8D437F)
class AppColorSchemes {
  // Light M3 Scheme
  static const ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF8D437F),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFD7F1),
    onPrimaryContainer: Color(0xFF370038),
    secondary: Color(0xFF705765),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFBD9EC),
    onSecondaryContainer: Color(0xFF281521),
    tertiary: Color(0xFF7E5538),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFDCC7),
    onTertiaryContainer: Color(0xFF301401),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    surface: Color(0xFFFFF7F9),
    onSurface: Color(0xFF201A1D),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFFFF0F5),
    surfaceContainer: Color(0xFFF9EAEF),
    surfaceContainerHigh: Color(0xFFF4E5EA),
    surfaceContainerHighest: Color(0xFFEEDFE4),
    outline: Color(0xFF82737A),
    outlineVariant: Color(0xFFD4C2CB),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF352E32),
    onInverseSurface: Color(0xFFFAEEF2),
    inversePrimary: Color(0xFFFFABEE),
  );

  // Dark M3 Scheme
  static const ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFFABEE),
    onPrimary: Color(0xFF56124E),
    primaryContainer: Color(0xFF712B66),
    onPrimaryContainer: Color(0xFFFFD7F1),
    secondary: Color(0xFFDEBDCF),
    onSecondary: Color(0xFF3F2A37),
    secondaryContainer: Color(0xFF57404E),
    onSecondaryContainer: Color(0xFFFBD9EC),
    tertiary: Color(0xFFF1BA98),
    onTertiary: Color(0xFF48280F),
    tertiaryContainer: Color(0xFF633E23),
    onTertiaryContainer: Color(0xFFFFDCC7),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF171215),
    onSurface: Color(0xFFEEDFE4),
    surfaceContainerLowest: Color(0xFF120D10),
    surfaceContainerLow: Color(0xFF201A1D),
    surfaceContainer: Color(0xFF241E21),
    surfaceContainerHigh: Color(0xFF2F282C),
    surfaceContainerHighest: Color(0xFF3A3337),
    outline: Color(0xFF9C8D95),
    outlineVariant: Color(0xFF4F4349),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFEEDFE4),
    onInverseSurface: Color(0xFF352E32),
    inversePrimary: Color(0xFF8D437F),
  );
}
